;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        abbrev-prefix-mark
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        duplicate-current-line-or-region
        evil-numbers/dec-at-pt
        evil-numbers/inc-at-pt
        find-tag
        forward-same-syntax
        increase-indentation
        indent-for-tab-command
        indent-new-comment-line
        isearch-backward-regexp
        isearch-exit
        isearch-forward-regexp
        isearch-repeat-backward
        kill-region
        kill-region-or-line
        kill-ring-save-region-or-line
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        nav-backward-line
        nav-forward-line
        nav-next-line
        nav-previous-line
        py-electric-backspace
        py-electric-colon
        py-electric-comment
        py-electric-delete
        py-indent-line
        py-newline-and-indent
        toggle-quotes
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key-briefly
        go-to-next-window
        ido-find-file
        isearch-abort
        isearch-delete-char
        isearch-other-control-char
        isearch-printing-char
        kill-rectangle
        mc/mark-all-in-region
        mc/mark-next-like-this-skip
        mc/mark-next-lines
        mc/mark-previous-lines
        mc/skip-and-mark-next-like-this
        mc/skip-and-mark-previous-like-this
        mc/unmark-next-like-this
        nav-backward-paragraph
        smex
        text-scale-increase
        undo-tree-visualize
        ))
