#!/bin/bash

FOLDERS="chaos code config literature pwnies study texmf"

for f in $FOLDERS ; do
  echo "=== Backing up $f ==="
  hindsight snapshot $f ~/$f
done

echo "=== Sealing database ==="
hindsight seal
