;; Navigation
(global-set-key [(meta control up)]      'pager-half-page-down)
(global-set-key [(meta control down)]    'pager-half-page-up)
(global-set-key [(meta shift up)] 'scroll-down-one)
(global-set-key [(meta shift down)]      'scroll-up-one)
(global-set-key [(meta up)]              'scroll-previous-line)
(global-set-key [(meta down)]            'scroll-next-line)
(global-set-key [(meta left)]            '(lambda () (interactive) (scroll-right 5)))
(global-set-key [(meta right)]           '(lambda () (interactive) (scroll-left 5)))
(global-set-key [(meta down)]            'scroll-next-line)
(global-set-key "\M-p"                   'backward-paragraph)
(global-set-key "\M-n"                   'forward-paragraph)
(global-set-key (kbd "<XF86Back>")       'backward-word)
(global-set-key (kbd "<XF86Forward>")    'forward-word)

(global-set-key (kbd "C--")              'text-scale-decrease)
(global-set-key (kbd "C-+")              'text-scale-increase)

(global-set-key "\C-o"                   'go-to-next-window)
(global-set-key "\C-\M-o"                'go-to-prev-window)
(global-set-key [(control shift o)]      'flip-next)
(global-set-key [(control shift meta o)] 'flip-previous)

(global-set-key [(control shift y)]      'yank-rectangle)
(global-set-key [(control shift w)]      'kill-rectangle)

(global-set-key [(control shift up)]     'move-line-or-lines-one-up)
(global-set-key [(control shift down)]   'move-line-or-lines-one-down)
(global-set-key (kbd "M-SPC")            'hippie-expand)
(global-set-key "\M-g"                   'goto-line)
(global-set-key "\C-q"                   'comment-or-uncomment-region-or-line)
(global-set-key [(control s)]            'isearch-forward-regexp)
(global-set-key [(control r)]            'isearch-backward-regexp)
(global-set-key [(control w)]            'kill-region-or-line)
(global-set-key [(meta w)]               'kill-ring-save-region-or-line)
(global-set-key [(control z)]            'ido-switch-buffer)
(global-set-key [(control return)]       'end-of-line-and-newline)
(global-set-key [(control shift return)] 'beginning-of-line-and-newline)
(global-set-key "\M-d"                   'duplicate-line)
(global-set-key [(control shift a)]      'align-all-strings)
(global-set-key (kbd "C-x C-a")          'anything)

(global-set-key (kbd "C-x C-r")          'rename-file-and-buffer)
(global-set-key (kbd "C-x C-m")          'move-file-and-buffer)

(global-set-key (kbd "<f5>")             'shell)
(global-set-key (kbd "C-x C-n")          'new-note)
(global-set-key (kbd "C-0")              'insert-zero)
(global-set-key (kbd "C-x C-t")
                '(lambda () (interactive)
                   (find-file "/home/mortenbp/notes/tasks.org")))

(global-set-key [(meta control right)]   'evil-numbers/inc-at-pt)
(global-set-key [(meta control left)]    'evil-numbers/dec-at-pt)
(global-set-key (kbd "<f7>")             'clipboard-kill-ring-save)
(global-set-key (kbd "<f8>")             'clipboard-yank)
